spring.application.name=api-gateway

server.port=8080

##################################################
# JWT
##################################################

application.security.jwt.secret-key=ZmY4NzM0N2NkMjYxODQ3YmFkYjNmNTI4ZDI4NmQ5Mjg0NWE4MzQ2OTQ3NmUyOGM0NTBhZGUxNzVjN2U3MjIwYQ==

application.security.jwt.expiration=86400000

##################################################
# Gateway Routes
##################################################

spring.cloud.gateway.routes[0].id=identity-auth
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id=identity-users
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.routes[2].id=identity-profile
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/profile/**