spring.application.name=maintenance-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/maintenance_db
spring.datasource.username=maintenance_user
spring.datasource.password=maintenance_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
